LF-10909-10: vvcam: ov2775: Fix build issues with upstream kernel next-20231129
The functions of the ov2775 is only called locally and does not need to be global.
Since there is no external prototype, gcc warns about the non-static
definition.

vvcam/v4l2/sensor/ov2775/ov2775_mipi_v3.c:355:5: error: no previous prototype for 'ov2775_get_clk' [-Werror=missing-prototypes]

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>