LF-11637: capture: vvcam: Fix isp vvcam build error
Fix build issue with upstream kernel next-20240220.

Caused by the commit:
d26270061ae6 ("string: Remove strlcpy()")

Build errors:
verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c: In function
'vidioc_enum_input': verisilicon_sw_isp_vvcam/vvcam/v4l2/video/video.c:
1327:9: error: implicit declaration of function 'strlcpy';
did you mean 'strncpy'? [-Werror=implicit-function-declaration]
strlcpy(input->name, "camera", sizeof(input->name));
   ^~~~~~~
strncpy cc1: all warnings being treated as errors

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>