LF-10909-3: vvcam: isp_mi: Fix build issues with upstream kernel next-20231129
The functions of the isp_mi are only called locally and do not need to be global.
Since there is no external prototype, gcc warns about the non-static
definition.

vvcam/v4l2/isp/isp_miv1.c:61:5: error: no previous prototype for 'getRawBit' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_miv1.c:123:5: error: no previous prototype for 'getScaleFactor' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_miv1.c:133:5: error: no previous prototype for 'set_scaling' [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>