LF-10909-8: vvcam: isp_rgbgamma: Fix build issues with upstream kernel next-20231129
This functions of isp_rgbgamma are only defined but not called, and all the warnings
will be treated as errors. And those are just used under the mocro ISP_RGBGC.

vvcam/v4l2/isp/isp_rgbgamma.c:140:12: error: 'isp_s_rgbgammaWriteData' defined but not used [-Werror=unused-function]
vvcam/v4l2/isp/isp_rgbgamma.c:94:12: error: 'isp_s_rgbgammapx' defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>