LF-10909-4: vvcam: isp_wdr3: Fix build issues with upstream kernel next-20231129
The functions of the isp_wdr3 are only called locally and do not need to be global.
Since there is no external prototype, gcc warns about the non-static
definition.

vvcam/v4l2/isp/isp_wdr3.c:75:6: error: no previous prototype for 'wdr3_hw_init' [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>