LF-11437: vvcam: Fixed the build breaks
Fix the vvcam build breaks, these error occurs because build warnings
were treated as errors.

Build Errors:
isp_ioctl.c:1121:5: error: no previous prototype for 'isp_exp_control'
[-Werror=missing-prototypes]
isp_ioctl.c:1251:5: error: no previous prototype for 'isp_hist_control'
[-Werror=missing-prototypes]

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>