LF-10909-1: vvcam: dwe: Fix build issues with upstream kernel next-20231129
The functions of the dwe only called locally and do not need to be global.
Since there is no external prototype, gcc warns about the non-static
definition.

vvcam/v4l2/dwe/dwe_driver_of.c:65:5: error: no previous prototype for 'dwe_subscribe_event' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_driver_of.c:71:5: error: no previous prototype for 'dwe_unsubscribe_event' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_driver_of.c:335:5: error: no previous prototype for 'dwe_hw_probe' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_driver_of.c:474:5: error: no previous prototype for 'dwe_hw_remove' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_driver_of.c:84:6: error: no previous prototype for 'dwe_ioctl' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_driver_of.c:141:5: error: no previous prototype for 'dwe_set_stream' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_ioctl.c:170:5: error: no previous prototype for 'dwe_start' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_ioctl.c:176:5: error: no previous prototype for 'dwe_stop' [-Werror=missing-prototypes]
vvcam/v4l2/dwe/dwe_ioctl.c:225:5: error: no previous prototype for 'dwe_ioc_qcap' [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>