LF-10909-2: vvcam: isp: Fix build issues with upstream kernel next-20231129
The functions of the ISP are only called locally and do not need to be
global. Since there is no external prototype, gcc warns about the
non-static definition.

vvcam/v4l2/isp/isp_driver_of.c:82:6: error: no previous prototype for 'isp_ioctl' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_driver_of.c:145:5: error: no previous prototype for 'isp_set_stream' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_driver_of.c:537:5: error: no previous prototype for 'isp_hw_probe' [-Werror=missing-prototypes]
vvcam/v4l2/isp/isp_driver_of.c:696:5: error: no previous prototype for 'isp_hw_remove' [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>