LF-10909-11: vvcam: ar1335: Fix build issues with upstream kernel next-20231129
The function of the ar1335 is only called locally and does not need to be
global. Since there is no external prototype, gcc warns about the
non-static definition.

vvcam/v4l2/sensor/ar1335/ar1335_mipi_v3.c:226:5: error: no previous prototype for 'ar1335_get_clk' [-Werror=missing-prototypes]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>