LF-10909-5: vvcam: isp_3dnr: Fix build issues with upstream kernel next-20231129
This function of isp_3dnr is only defined but not call, and all the warnings
will be treated as errors. So it is just used under the mocro ISP_3DNR.

vvcam/v4l2/isp_3dnr.c:63:13: error: 'dnr3_hw_init' defined but not used [-Werror=unused-function]
cc1: all warnings being treated as errors

Caused by the commits:
89741e7e42f6a (Makefile: Enable -Wstringop-overflow globally)
0168bf99702aa (Makefile.extrawarn: turn on missing-prototypes globally)

Signed-off-by: Alice Yuan <alice.yuan@nxp.com>
Reviewed-by: Robby Cai <robby.cai@nxp.com>